name: 🐙 Request a new extension method
description: Have an idea to simplify a very repetative process for a specific type? While extension methods have a bad reputation, when implemented properly, they can be very powerful.
labels: [enhancement,extensions,under review]
body:
  - type: dropdown
    id: version
    attributes:
      label: 🔢 Version
      description: Which version of Mauve are you currently using?
      options:
        - 🐣 Pre-Release
    validations:
      required: true
  - type: input
    attributes:
      label: 🦖 What type is this extension method for?
      description: Please include the namespace and type.
  - type: textarea
    attributes:
      label: 😭 What problem does your proposition aim to solve?
      description: Please give a brief explanation and a sample implementation.
  - type: textarea
    attributes:
      label: 📝 How would you like the extension method to work?
      description: Please give a brief explanation and a sample implementation.